{% set name = "mando" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 539659d9a2fdc6c9a188211c58f381e0dafe9597085174c5472eb1ed0224b6b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  build:
    - python
    - setuptools
  run:
    - six
    - python
  host:
    - python
    - pip

test:
  # source_files:
  #   - tests
  imports:
    - mando
    - mando.core
    - mando.napoleon
    - mando.utils
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs mando.tests

about:
  home: https://github.com/rubik/mando
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mando is a wrapper around argparse.
  description: |
    mando is a wrapper around argparse, and allows you to write complete
    CLI applications in seconds while maintaining all the flexibility.
  doc_url: https://mando.readthedocs.io
  dev_url: https://github.com/rubik/mando

extra:
  recipe-maintainers:
    - igortg