travis:
  secure:
    BINSTAR_TOKEN: id77KBgiimOOl+4XTfc3+gZCgg9OLI4Glu5hcKl6RvIIihDNpEH+VIIzWx0fB/kDnAFdc/nTdB+uFZ0blfdJHfpdHVAvI2rXjjAhTZglpcuaP17NQ/3jCzmpAhBNhWE9mW4ReCzzMp3PVJAXmXzWxTvNT+EQfYwqjyxCmXDwbZzPrVGXZiI4p7CK0U6GPuTQcThuWSJheBbjuQnJKZKVqEc+neBKuNnJAPB56TSnKYIwhr59Sf1UPyoLZ7LSFviWaqs9Ehsqo4kguiZAtfbFpsAWvB0WG584GhsXP4zonVaZtiRuT5o7o2QpgSH1LGFhSjV0Ko6z0wMqPrcosIhVdQMXtpmFjJ/U38SJLrZ+hzwEO2m8LZSoBxU5XF1ABqAbiS1CgPWHRSHyedjthQborXJINZERhJ/NJAVNbWG1z/lC1PT8fdeX0aZTsZMt+/FC4f64J0ONLmrHG3bgwb1ase6lMWWk9KKEPiiKSmQbSZKRdXBnaxYSTvB899e8Ttgler464+41KlBYsJHjxT63Q0WRvlvnr35WvoaUyv790KkhRRHeBMaHTT5KJNtpYlCQ7cjsXqxTVZ9trKdy37BhyZ9/K7N2xEg5V+Z6FViSKf0s/2By1uuVOsfZyKUcNnlxxP60aoWihj8P7GF1fMR3AqkMgHuHc50iQPVA0uhwdd8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
