travis:
  secure:
    BINSTAR_TOKEN: X1cGn6QS/387Ps25TfNNxLek8aKZ7bf9i13pgN60xXKku73q5UL08Z9ZdWmLo6jMMCsIehQNk6qIu6oszIdSTk/8P5zDqho3J1aHzE6K3t1pNUDej+McOzfuJpdpn6nqEI/HdmnnZ1iczf1+CA9qtV5Uqi4l/sU0QsYp7DPsPDNJnw33tLNVHptMGSTDxuZUjVHPF84oPxm3hgnlnQpZ6P9naz9QGtA+GHdvgjji9xEu+ss/sMvHSvRz2zJSQ+GWr6cM4ykAZSDgjrgRltCyzRE2sHdpiLs4/ZeqxfQ+5pec0spKpZwFcPXaw85EpP2vK/ttgEdAN4mxuAKxaWR/GLTbJa34pE8iPKEG3Z5tEGtx78y1+FZvzw+gun4fSslGWpRUi1n8ZXrtH1vbGpYJSugOL5u2VMs+Ublq1UbuYOyipR9IzVLIz0W6TPtEO9UBYq7sp9Yc/DyDFdNUSWKJyiXozMfAYkNWlNf1IY3sczhoKNVzg6ipsuaFVFp9Jya6ow6fZk8xZh0GlyfNmD0tNnTCQWkeLwt0Zm+PaNDzcJmLy8ZXda2qYUMYbATbqYHkp6YZozD5h/y4n6nIvBPNe7XzcHVbupWgKvXcz+ITik/8VmdoZsN9sbSO+wOfcoLgvmsCf5wP1mhruCdx40ey8VeA89b8N8NUaIiTEEKdY2A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
